# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 14.0.1
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: Fastlane
          command: fastlane scan
          environment:
          SCAN_DEVICE: iPhone 13
          SCAN_SCHEMA: NewsWorld
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
